[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "clocks-and-timers"
version = "0.1.0"

[dependencies]
aux9 = { path = "auxiliary" }
cortex-m-rt = "0.6.3"
heapless = "0.6.0"
embedded-hal = "0.2.4"

[dependencies.morse_utils]
path = "../morse_utils"


